#!/bin/bash

set -o xtrace

echo "CONFIG" >&2

. /usr/share/debconf/confmodule

if [ -f /usr/share/debconf/confmodule ]; then
    echo "CONFIG 22 " >&2
    db_version 2.0
    db_input high usershub/URL_APPLICATION || true
    db_input high usershub/PASS_METHOD || true
    db_input high usershub/FILL_MD5_PASS || true
    db_input high usershub/COOKIE_EXPIRATION || true
    db_input low usershub/ACTIVATE_API || true
    db_input low usershub/ACTIVATE_APP || true
    db_input high usershub/SECRET_KEY || true
    db_go
fi
