Document: geonature-db
Title: Debian geonature-db Manual
Author: <insert document author here>
Abstract: This manual describes what geonature-db is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/geonature-db/geonature-db.sgml.gz

Format: postscript
Files: /usr/share/doc/geonature-db/geonature-db.ps.gz

Format: text
Files: /usr/share/doc/geonature-db/geonature-db.text.gz

Format: HTML
Index: /usr/share/doc/geonature-db/html/index.html
Files: /usr/share/doc/geonature-db/html/*.html
